# version: '3.8'

services:
  test-node:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: hotstuff-test
    environment:
      - RUST_LOG=info
    volumes:
      - ./logs:/app/logs
    networks:
      - hotstuff-network

networks:
  hotstuff-network:
    driver: bridge
